#!/bin/bash
set -e

echo "======================================================="
echo "        LocalAI Server Setup"
echo "======================================================="

echo ""
echo "[0/7] Installing system dependencies (cmake, git, etc)..."
if command -v apt-get &> /dev/null; then
    sudo apt-get update && sudo apt-get install -y cmake git build-essential
elif command -v dnf &> /dev/null; then
    sudo dnf install -y cmake git gcc-c++ make
elif command -v pacman &> /dev/null; then
    sudo pacman -S --needed cmake git base-devel
elif command -v brew &> /dev/null; then
    brew install cmake git
else
    echo "WARNING: Could not detect package manager. Please ensure cmake and git are installed."
fi

echo ""
echo "[1/7] Creating Python Virtual Environment..."
python3 -m venv venv
source venv/bin/activate

echo ""
echo "[2/7] Installing base dependencies..."
pip install --upgrade pip setuptools wheel

# Install everything except llama-cpp-python (built separately below,
# with hardware-specific flags).
grep -v "^llama-cpp-python" requirements.txt > /tmp/requirements-base.txt
pip install -r /tmp/requirements-base.txt

echo ""
echo "[3/7] Selecting embedding model..."
echo ""
echo "Embedding models are used for semantic search (RAG) of conversation history."
echo "Choose one:"
echo ""
echo "  1) BAAI/bge-small-en-v1.5       - General purpose, 384-dim, fast, small (default)"
echo "  2) microsoft/codebert-base       - Code-specialized, 768-dim, better for code"
echo "  3) sentence-transformers/all-MiniLM-L6-v2 - General, 384-dim, popular"
echo "  4) BAAI/bge-base-en-v1.5        - General, 768-dim, higher quality"
echo "  5) Custom model path/name"
echo ""
read -p "Select embedding model [1-5] (default: 1): " EMBED_CHOICE
EMBED_CHOICE=${EMBED_CHOICE:-1}

case $EMBED_CHOICE in
    1) EMBED_MODEL="BAAI/bge-small-en-v1.5" ;;
    2) EMBED_MODEL="microsoft/codebert-base" ;;
    3) EMBED_MODEL="sentence-transformers/all-MiniLM-L6-v2" ;;
    4) EMBED_MODEL="BAAI/bge-base-en-v1.5" ;;
    5)
        read -p "Enter model name or local path: " EMBED_MODEL
        ;;
    *)
        echo "Invalid choice, using default (1)"
        EMBED_MODEL="BAAI/bge-small-en-v1.5"
        ;;
esac

echo "Selected: $EMBED_MODEL"

# Write to .env for persistence
cat > .env <<EOF
# Generated by setup.sh
LLM_EMBEDDING_MODEL=$EMBED_MODEL
LLM_EMBEDDING_MODEL_CODE=$EMBED_MODEL
LLM_TOOL_TIMEOUT_SECONDS=30.0
LLM_TOOL_MAX_RETRIES=2
EOF

echo ""
echo "[4/7] Detecting GPU backend..."

if command -v nvidia-smi &> /dev/null; then
    echo " NVIDIA GPU detected — building with CUDA"
    BACKEND_CMAKE_ARGS="-DGGML_CUDA=on"
    BACKEND_BUILD_PARALLEL=""
else
    echo " AMD / Intel / Generic GPU detected — building with Vulkan"
    BACKEND_CMAKE_ARGS="-DGGML_VULKAN=on"
    BACKEND_BUILD_PARALLEL="1"
fi

echo ""
echo "[5/7] Building llama-cpp-python (Python bindings — still used for the"
echo "      exact-vocab tokenizer and model catalog/download, just not for"
echo "      serving completions anymore)..."

export CMAKE_ARGS="$BACKEND_CMAKE_ARGS"
if [ -n "$BACKEND_BUILD_PARALLEL" ]; then
    export CMAKE_BUILD_PARALLEL_LEVEL="$BACKEND_BUILD_PARALLEL"
fi

pip install llama-cpp-python \
    --no-cache-dir \
    --force-reinstall \
    --no-binary llama-cpp-python

echo ""
echo "[7/8] Building native llama-server (this is what actually serves"
echo "      completions now — it reads each GGUF's own chat template, which"
echo "      is what makes tool-calling work across different models instead"
echo "      of requiring a hand-picked format per model)..."

if [ ! -d "llama.cpp" ]; then
    git clone https://github.com/ggml-org/llama.cpp.git
fi

cmake llama.cpp -B llama.cpp/build $BACKEND_CMAKE_ARGS -DBUILD_SHARED_LIBS=OFF
cmake --build llama.cpp/build --config Release --target llama-server \
    -j "${BACKEND_BUILD_PARALLEL:-$(nproc)}"

echo ""
echo "[8/8] Qdrant vector database setup..."
echo ""
echo "Qdrant is used for session memory / RAG. Choose one:"
echo ""
echo "  1) Docker (recommended) — runs Qdrant server on localhost:6333"
echo "  2) Embedded mode — no docker needed, but single-process only"
echo ""
read -p "Select Qdrant mode [1-2] (default: 1): " QDRANT_CHOICE
QDRANT_CHOICE=${QDRANT_CHOICE:-1}

if [ "$QDRANT_CHOICE" = "1" ]; then
    # Check if docker is available
    if command -v docker &> /dev/null && docker info &> /dev/null 2>&1; then
        echo " Docker available — will use Qdrant server mode"
        echo "LLM_VECTOR_BACKEND=qdrant" >> .env
        echo "LLM_VECTOR_DB_PATH=http://localhost:6333" >> .env
        echo "LLM_QDRANT_SERVER_URL=http://localhost:6333" >> .env
        # Add helper to start.sh
    else
        echo " Docker not available or not running — falling back to embedded mode"
        echo "LLM_VECTOR_BACKEND=qdrant" >> .env
        echo "LLM_VECTOR_DB_PATH=./qdrant_db" >> .env
    fi
else
    echo " Using embedded Qdrant mode"
    echo "LLM_VECTOR_BACKEND=qdrant" >> .env
    echo "LLM_VECTOR_DB_PATH=./qdrant_db" >> .env
fi

# Session limits
echo "LLM_MAX_SESSIONS_PER_USER=50" >> .env
echo "LLM_SESSION_TTL_DAYS=30" >> .env

echo ""
echo "Verifying llama-cpp-python installation..."

python - <<'PY'
from llama_cpp import llama_supports_gpu_offload

print()
print("llama.cpp GPU offload support:", llama_supports_gpu_offload())
print()
PY

echo "======================================================="
echo " Setup complete!"
echo "======================================================="
echo ""
echo "Before starting, set an API key (required — the server is"
echo "reachable from your whole network):"
echo ""
echo "  export LLM_API_KEY=\"\$(python -c 'import secrets; print(secrets.token_urlsafe(32))')\""
echo "  echo \$LLM_API_KEY   # save this — every client needs it"
echo ""
echo "Then start the server with (auto-starts Qdrant if using docker mode):"
echo "  ./start.sh"
echo ""