@echo off
setlocal EnableExtensions

echo =======================================================
echo          LocalAI Server Setup
echo =======================================================
echo.

echo [1/5] Creating Python Virtual Environment...
if not exist venv (
    python -m venv venv
)

call venv\Scripts\activate.bat

echo.
echo [2/5] Upgrading Python build tools...
python -m pip install --upgrade pip setuptools wheel

echo.
echo [3/5] Installing base dependencies...

if exist requirements.txt (
    python -m pip install -r requirements.txt
)

echo.
echo [4/5] Selecting embedding model...
echo.
echo Embedding models are used for semantic search (RAG) of conversation history.
echo Choose one:
echo.
echo   1) BAAI/bge-small-en-v1.5       - General purpose, 384-dim, fast, small (default)
echo   2) microsoft/codebert-base       - Code-specialized, 768-dim, better for code
echo   3) sentence-transformers/all-MiniLM-L6-v2 - General, 384-dim, popular
echo   4) BAAI/bge-base-en-v1.5        - General, 768-dim, higher quality
echo   5) Custom model path/name
echo.

set /p EMBED_CHOICE=Select embedding model [1-5] (default: 1): 
if "%EMBED_CHOICE%"=="" set EMBED_CHOICE=1

if "%EMBED_CHOICE%"=="1" set EMBED_MODEL=BAAI/bge-small-en-v1.5
if "%EMBED_CHOICE%"=="2" set EMBED_MODEL=microsoft/codebert-base
if "%EMBED_CHOICE%"=="3" set EMBED_MODEL=sentence-transformers/all-MiniLM-L6-v2
if "%EMBED_CHOICE%"=="4" set EMBED_MODEL=BAAI/bge-base-en-v1.5
if "%EMBED_CHOICE%"=="5" (
    set /p EMBED_MODEL=Enter model name or local path: 
)
if "%EMBED_MODEL%"=="" set EMBED_MODEL=BAAI/bge-small-en-v1.5

echo Selected: %EMBED_MODEL%

REM Write to .env for persistence
echo # Generated by setup.bat > .env
echo LLM_EMBEDDING_MODEL=%EMBED_MODEL% >> .env
echo LLM_EMBEDDING_MODEL_CODE=%EMBED_MODEL% >> .env

echo.
echo =======================================================
echo Detecting GPU backend...
echo =======================================================

where nvidia-smi >nul 2>&1

if %ERRORLEVEL% EQU 0 (
    echo.
    echo NVIDIA GPU Detected!
    echo Building llama-cpp-python with CUDA...
    echo.

    set "CMAKE_ARGS=-DGGML_CUDA=on"

    python -m pip install llama-cpp-python ^
        --no-cache-dir ^
        --force-reinstall ^
        --no-binary llama-cpp-python

) else (
    echo.
    echo AMD / Intel / Generic GPU Detected!
    echo Building llama-cpp-python with Vulkan...
    echo.

    set "CMAKE_ARGS=-DGGML_VULKAN=on"
    set "CMAKE_BUILD_PARALLEL_LEVEL=1"

    python -m pip install llama-cpp-python ^
        --no-cache-dir ^
        --force-reinstall ^
        --no-binary llama-cpp-python
)

echo.
echo [5/5] Verifying installation...
echo.

python -c "from llama_cpp import llama_supports_gpu_offload; print('GPU offload support:', llama_supports_gpu_offload())"

if %ERRORLEVEL% NEQ 0 (
    echo.
    echo =======================================================
    echo Installation verification FAILED.
    echo =======================================================
    echo.
    pause
    exit /b 1
)

echo.
echo =======================================================
echo Setup complete!
echo =======================================================
echo.
echo Before starting, set an API key ^(required — the server is
echo reachable from your whole network^):
echo.
echo     set LLM_API_KEY=your-generated-key-here
echo.
echo Then start the server with:
echo.
echo     start.bat
echo.
echo =======================================================

pause
endlocal